/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedLikedRouteImport } from './routes/_authenticated/liked'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPlaylistsIndexRouteImport } from './routes/_authenticated/playlists.index'
import { Route as AuthenticatedMoodsIndexRouteImport } from './routes/_authenticated/moods.index'
import { Route as AuthenticatedPlaylistsIdRouteImport } from './routes/_authenticated/playlists.$id'
import { Route as AuthenticatedMoodsSlugRouteImport } from './routes/_authenticated/moods.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLikedRoute = AuthenticatedLikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaylistsIndexRoute =
  AuthenticatedPlaylistsIndexRouteImport.update({
    id: '/playlists/',
    path: '/playlists/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMoodsIndexRoute = AuthenticatedMoodsIndexRouteImport.update({
  id: '/moods/',
  path: '/moods/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaylistsIdRoute =
  AuthenticatedPlaylistsIdRouteImport.update({
    id: '/playlists/$id',
    path: '/playlists/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMoodsSlugRoute = AuthenticatedMoodsSlugRouteImport.update({
  id: '/moods/$slug',
  path: '/moods/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/liked': typeof AuthenticatedLikedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/moods/$slug': typeof AuthenticatedMoodsSlugRoute
  '/playlists/$id': typeof AuthenticatedPlaylistsIdRoute
  '/moods/': typeof AuthenticatedMoodsIndexRoute
  '/playlists/': typeof AuthenticatedPlaylistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/liked': typeof AuthenticatedLikedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/moods/$slug': typeof AuthenticatedMoodsSlugRoute
  '/playlists/$id': typeof AuthenticatedPlaylistsIdRoute
  '/moods': typeof AuthenticatedMoodsIndexRoute
  '/playlists': typeof AuthenticatedPlaylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/liked': typeof AuthenticatedLikedRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/moods/$slug': typeof AuthenticatedMoodsSlugRoute
  '/_authenticated/playlists/$id': typeof AuthenticatedPlaylistsIdRoute
  '/_authenticated/moods/': typeof AuthenticatedMoodsIndexRoute
  '/_authenticated/playlists/': typeof AuthenticatedPlaylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/home'
    | '/library'
    | '/liked'
    | '/search'
    | '/moods/$slug'
    | '/playlists/$id'
    | '/moods/'
    | '/playlists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/home'
    | '/library'
    | '/liked'
    | '/search'
    | '/moods/$slug'
    | '/playlists/$id'
    | '/moods'
    | '/playlists'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/home'
    | '/_authenticated/library'
    | '/_authenticated/liked'
    | '/_authenticated/search'
    | '/_authenticated/moods/$slug'
    | '/_authenticated/playlists/$id'
    | '/_authenticated/moods/'
    | '/_authenticated/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/liked': {
      id: '/_authenticated/liked'
      path: '/liked'
      fullPath: '/liked'
      preLoaderRoute: typeof AuthenticatedLikedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playlists/': {
      id: '/_authenticated/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof AuthenticatedPlaylistsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moods/': {
      id: '/_authenticated/moods/'
      path: '/moods'
      fullPath: '/moods/'
      preLoaderRoute: typeof AuthenticatedMoodsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playlists/$id': {
      id: '/_authenticated/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof AuthenticatedPlaylistsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moods/$slug': {
      id: '/_authenticated/moods/$slug'
      path: '/moods/$slug'
      fullPath: '/moods/$slug'
      preLoaderRoute: typeof AuthenticatedMoodsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedLikedRoute: typeof AuthenticatedLikedRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedMoodsSlugRoute: typeof AuthenticatedMoodsSlugRoute
  AuthenticatedPlaylistsIdRoute: typeof AuthenticatedPlaylistsIdRoute
  AuthenticatedMoodsIndexRoute: typeof AuthenticatedMoodsIndexRoute
  AuthenticatedPlaylistsIndexRoute: typeof AuthenticatedPlaylistsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedLikedRoute: AuthenticatedLikedRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedMoodsSlugRoute: AuthenticatedMoodsSlugRoute,
  AuthenticatedPlaylistsIdRoute: AuthenticatedPlaylistsIdRoute,
  AuthenticatedMoodsIndexRoute: AuthenticatedMoodsIndexRoute,
  AuthenticatedPlaylistsIndexRoute: AuthenticatedPlaylistsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
